# Generated by Django 5.0.1 on 2024-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_course_created_at_course_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('certification', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
